# Carbon footprint Prediction

In [38]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [17]:
df = pd.read_csv('data/carbon_footprint_india.csv')
df.head()

Year   State/UT       Sector  CO₂ Emissions (Million Tonnes)  \
0  2006    Gujarat       Energy                          224.26   
1  2019  Jharkhand        Waste                          132.17   
2  2014  Meghalaya    Transport                          341.46   
3  2010     Kerala       Energy                           71.69   
4  2007    Tripura  Agriculture                          430.54   

   CH₄ Emissions (Million Tonnes CO₂e)  N₂O Emissions (Million Tonnes CO₂e)  \
0                                14.90                                 9.02   
1                                 4.20                                 6.28   
2                                12.53                                 9.38   
3                                47.87                                13.96   
4                                15.94                                 9.69   

   Energy Consumption (TWh)  Electricity Generation (TWh)  \
0                     40.25                        279.66   
1                    152.16                        188.59   
2                    269.18                         81.57   
3                    373.22                        174.96   
4                    416.05                         86.60   

   Fossil Fuel Consumption (MTOE)  Vehicle Count (Million Units)  \
0                          107.25                          47.16   
1                          218.93                          35.95   
2                           17.66                          30.39   
3                           14.73                           8.88   
4                          162.34                          23.88   

   Industrial Output (GDP Contribution in ₹ Cr)  \
0                                       9144.38   
1                                      36044.41   
2                                      36520.51   
3                                      71955.77   
4                                      68045.72   

   Agricultural Land Usage (Million Hectares)  \
0                                       48.15   
1                                       46.64   
2                                       42.70   
3                                       37.77   
4                                       27.01   

   Deforestation Rate (sq. km per year)  Waste Generation (Million Tonnes)  \
0                                107.42                              47.20   
1                                 27.46                              35.83   
2                                 31.41                              27.45   
3                                 51.19                              91.14   
4                                 58.79                              61.55   

   Renewable Energy Share (%)  
0                        6.88  
1                       39.76  
2                       18.72  
3                       69.71  
4                       59.24

In [18]:
GWP_CH4 = 28  # Methane GWP
GWP_N2O = 265  # Nitrous Oxide GWP

# Calculate total carbon footprint
df["Carbon Footprint (Million Tonnes CO₂e)"] = (
    df["CO₂ Emissions (Million Tonnes)"] +
    (df["CH₄ Emissions (Million Tonnes CO₂e)"] * GWP_CH4) +
    (df["N₂O Emissions (Million Tonnes CO₂e)"] * GWP_N2O)
)

In [19]:
df.head()

Year   State/UT       Sector  CO₂ Emissions (Million Tonnes)  \
0  2006    Gujarat       Energy                          224.26   
1  2019  Jharkhand        Waste                          132.17   
2  2014  Meghalaya    Transport                          341.46   
3  2010     Kerala       Energy                           71.69   
4  2007    Tripura  Agriculture                          430.54   

   CH₄ Emissions (Million Tonnes CO₂e)  N₂O Emissions (Million Tonnes CO₂e)  \
0                                14.90                                 9.02   
1                                 4.20                                 6.28   
2                                12.53                                 9.38   
3                                47.87                                13.96   
4                                15.94                                 9.69   

   Energy Consumption (TWh)  Electricity Generation (TWh)  \
0                     40.25                        279.66   
1                    152.16                        188.59   
2                    269.18                         81.57   
3                    373.22                        174.96   
4                    416.05                         86.60   

   Fossil Fuel Consumption (MTOE)  Vehicle Count (Million Units)  \
0                          107.25                          47.16   
1                          218.93                          35.95   
2                           17.66                          30.39   
3                           14.73                           8.88   
4                          162.34                          23.88   

   Industrial Output (GDP Contribution in ₹ Cr)  \
0                                       9144.38   
1                                      36044.41   
2                                      36520.51   
3                                      71955.77   
4                                      68045.72   

   Agricultural Land Usage (Million Hectares)  \
0                                       48.15   
1                                       46.64   
2                                       42.70   
3                                       37.77   
4                                       27.01   

   Deforestation Rate (sq. km per year)  Waste Generation (Million Tonnes)  \
0                                107.42                              47.20   
1                                 27.46                              35.83   
2                                 31.41                              27.45   
3                                 51.19                              91.14   
4                                 58.79                              61.55   

   Renewable Energy Share (%)  Carbon Footprint (Million Tonnes CO₂e)  
0                        6.88                                 3031.76  
1                       39.76                                 1913.97  
2                       18.72                                 3178.00  
3                       69.71                                 5111.45  
4                       59.24                                 3444.71

In [20]:
df.drop(columns=['Year'], inplace=True)

In [21]:
df = pd.get_dummies(df, columns=['Sector'], drop_first=True)

In [22]:
df = pd.get_dummies(df, columns=['State/UT'], drop_first=True)

In [23]:
df.head()

CO₂ Emissions (Million Tonnes)  CH₄ Emissions (Million Tonnes CO₂e)  \
0                          224.26                                14.90   
1                          132.17                                 4.20   
2                          341.46                                12.53   
3                           71.69                                47.87   
4                          430.54                                15.94   

   N₂O Emissions (Million Tonnes CO₂e)  Energy Consumption (TWh)  \
0                                 9.02                     40.25   
1                                 6.28                    152.16   
2                                 9.38                    269.18   
3                                13.96                    373.22   
4                                 9.69                    416.05   

   Electricity Generation (TWh)  Fossil Fuel Consumption (MTOE)  \
0                        279.66                          107.25   
1                        188.59                          218.93   
2                         81.57                           17.66   
3                        174.96                           14.73   
4                         86.60                          162.34   

   Vehicle Count (Million Units)  \
0                          47.16   
1                          35.95   
2                          30.39   
3                           8.88   
4                          23.88   

   Industrial Output (GDP Contribution in ₹ Cr)  \
0                                       9144.38   
1                                      36044.41   
2                                      36520.51   
3                                      71955.77   
4                                      68045.72   

   Agricultural Land Usage (Million Hectares)  \
0                                       48.15   
1                                       46.64   
2                                       42.70   
3                                       37.77   
4                                       27.01   

   Deforestation Rate (sq. km per year)  ...  State/UT_Puducherry  \
0                                107.42  ...                    0   
1                                 27.46  ...                    0   
2                                 31.41  ...                    0   
3                                 51.19  ...                    0   
4                                 58.79  ...                    0   

   State/UT_Punjab  State/UT_Rajasthan  State/UT_Sikkim  State/UT_Tamil Nadu  \
0                0                   0                0                    0   
1                0                   0                0                    0   
2                0                   0                0                    0   
3                0                   0                0                    0   
4                0                   0                0                    0   

   State/UT_Telangana  State/UT_Tripura  State/UT_Uttar Pradesh  \
0                   0                 0                       0   
1                   0                 0                       0   
2                   0                 0                       0   
3                   0                 0                       0   
4                   0                 1                       0   

   State/UT_Uttarakhand  State/UT_West Bengal  
0                     0                     0  
1                     0                     0  
2                     0                     0  
3                     0                     0  
4                     0                     0  

[5 rows x 46 columns]

In [24]:
X = df.drop(columns=['Carbon Footprint (Million Tonnes CO₂e)'])
Y = df['Carbon Footprint (Million Tonnes CO₂e)']

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [27]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [33]:
linear_model = LinearRegression()
linear_model.fit(X_train_scaled, Y_train)

LinearRegression()

In [34]:
tree_model = DecisionTreeRegressor(random_state=42)
tree_model.fit(X_train_scaled, Y_train)

DecisionTreeRegressor(random_state=42)

In [35]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, Y_train)

RandomForestRegressor(random_state=42)

In [37]:
Y_pred = linear_model.predict(X_test_scaled)
Y_pred

array([5051.33, 3530.23, 4850.84, ..., 5981.59, 2636.33, 6164.88])

In [39]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [40]:
print(f"{mae}, {mse}, {r2}")

2.7732767193811012e-12, 1.1888663047441193e-23, 1.0


In [41]:
Y_pred = tree_model.predict(X_test_scaled)
Y_pred

array([5116.22, 3602.14, 4972.44, ..., 6017.98, 2672.67, 6208.79])

In [42]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [43]:
print(f"{mae}, {mse}, {r2}")

82.5738, 10840.0223363, 0.9955045329961458


In [44]:
Y_pred = rf_model.predict(X_test_scaled)
Y_pred

array([5036.0842, 3495.7596, 4800.9821, ..., 5977.0251, 2643.6432,
       6187.766 ])

In [45]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [46]:
print(f"{mae}, {mse}, {r2}")

39.487226199999974, 2520.7744731802, 0.998954609306441
